#!/bin/bash

NAMESERVERS=("google-public-dns-a.google.com" "google-public-dns-b.google.com" "opendns.org" "1.1.1.1")

tLen=${#NAMESERVERS[@]}
declare -a dns

for (( i=0; i<${tLen}; i++));
do 
 ping -c1 -q ${NAMESERVERS[$i]} >/dev/null && dns[$i] ='ok'
done

for name in ${dns[@]};
  do
    echo $name
done